[package]
name = "smda"
description = "SMDA is a minimalist recursive disassembler library."
version = "0.1.5"
authors = ["Marirs <marirs@gmail.com>", "Andrey Mnatsakanov <andrey@3ig.kiev.ua>"]
include = ["assets", "src"]
keywords = ["smda", "disassembler", "cfg", "capstone"]
categories = ["parsing", "development-tools::debugging"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/marirs/smda-rs"
edition = "2018"

[dependencies]
capstone = "0.10.0"
data-encoding = "2.3.2"
goblin = { version = "0.4.3", features = ["alloc"] }
hex = "0.4.3"
itertools = "0.10.3"
maplit = "1.0.2"
regex = "1.5.4"
ring = "0.17.0-alpha.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.75"
thiserror = "1.0.30"

[lib]
name = "smda"
path = "src/lib.rs"
