[package]
name = "smda"
description = "SMDA is a minimalist recursive disassembler library."
version = "0.2.6"
authors = ["Marirs <marirs@gmail.com>", "Andrey Mnatsakanov <andrey@3ig.kiev.ua>"]
keywords = ["smda", "disassembler", "cfg", "capstone"]
categories = ["parsing", "development-tools::debugging"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/marirs/smda-rs"
homepage = "https://github.com/marirs/smda-rs"
include = ["assets", "src"]
edition = "2021"

[dependencies]
capstone = "0.10.0"
data-encoding = "2.3.2"
goblin = { version = "0.7.1", features = ["alloc"] }
hex = "0.4.3"
itertools = "0.10.3"
lazy_static = "1"
maplit = "1.0.2"
regex = "1.5.5"
ring = "0.17.0-alpha.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"

[lib]
name = "smda"
path = "src/lib.rs"

[profile.dev]
opt-level = 3

[profile.release]
codegen-units = 1
debug-assertions = false
debug = false
opt-level = 3
lto = true
